import = [
    #"~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
#startup_mode = "Fullscreen"
startup_mode = "Maximized"
decorations = "Full"

#decorations = "Buttonless" # macOS only
opacity=1
blur=true # macOS KDE/Wayland

[font]
#normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font Mono"

#regular
size = 22

#for video
# size = 35.0
