import = [
    #"~/.config/alacritty/themes/themes/coolnight.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
#startup_mode = "Fullscreen"
startup_mode = "Maximized"
decorations = "Full"

#decorations = "Buttonless" # macOS only
opacity=1
blur=true # macOS KDE/Wayland

[font]
#normal.family = "MesloLGS Nerd Font Mono"
#normal.family = "JetBrainsMono Nerd Font Mono"
#normal.family = "jetbrainsmono nerd font"
#normal.family = "JetBrainsMono Nerd Font"
#normal.family = "SauceCodePro Nerd Font"
#normal.family = "DejaVuSansM Nerd Font Mono"
#normal.family = "MesloLGM Nerd Font"
normal.family = "UbuntuMono Nerd Font Mono"
normal.style = "Regular"
#normal.style = "Bold"
#normal.style = "Medium"

#regular
size = 18

#for video
# size = 35.0

# Spawn new instance in same directory (Ctrl+Shift+Enter)
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# Toggle vi-mode copy/paste: Ctrl+Shift+Space
# To Copy, either use mouse and Ctrl+Shift+c, or enter vi-mode and use v, r,
# h,j,k,l, and y like in vi. 
#
#
